sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        user_block: 'admin/user_block.html.twig'
    default_controller: App\Controller\CustomCRUDController


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
