controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

redirect_all:
    path: /{url}
    controller: App\Controller\RedirectToSonataController::urlRedirect
    defaults:
        path: /admin
        permanent: true
    requirements:
        url: ".+"
